image: skylarkelty/moodle-gitlab

cache:
    paths:
        - vendor/

services:
    - mysql:latest

variables:
    MYSQL_ROOT_PASSWORD: "moodle_ci_password"

stages:
    - checks

before_script:
    - export MOODLE_BRANCH=MOODLE_31_STABLE
    - cd ~
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
    - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
    - moodle-plugin-ci install

linter:
    stage: checks
    script:
        - moodle-plugin-ci phplint
